hostnames = ["host0", "host1", "host2", "host3",
             "weak_0", "weak_1", "weak_2", "weak_3"]

build = ["script/build_envtest_geo.sh"]

log-dir = ["/users/Yunhao/log/"]
local-dir = ["/opt/chance/cob/target/debug/", "/opt/chance/cob/config/"]
remote-dir = ["/opt/chance/target_binary/", "/opt/chance/target_config/"]

config-files = ["envtest_geo.toml"]
binary-files = ["envtest_geo_client", "envtest_geo_server"]

client-args = ["--config", "/opt/chance/target_config/envtest_geo"]
server-args = ["--config", "/opt/chance/target_config/envtest_geo"]

server-hosts = ["host0", "host1", "host2", "host3"]
server-ports = ["10000", "10000", "10000", "10000"]

client-hosts = ["weak_0", "weak_1", "weak_2", "weak_3"]
client-latencies = ["2", "160", "192", "229"]
