hostnames = ["host0", "host1", "host2", "host3",
             "host4", "host5", "host6", "host7",
             "host8", "host9", "host10", "host11"]

build = ["script/build_envtest_geo.sh"]

log-dir = ["/users/Yunhao/log/"]
local-dir = ["/opt/home/cob/target/debug/", "/opt/home/cob/config/"]
remote-dir = ["/opt/home/target_binary/", "/opt/home/target_config/"]

config-files = ["envtest_geo.toml"]
binary-files = ["envtest_geo_client", "envtest_geo_server"]

client-args = ["--config", "/opt/home/target_config/envtest_geo"]
server-args = ["--config", "/opt/home/target_config/envtest_geo"]

server-hosts = ["host0", "host1", "host2", "host3",
                "host4", "host5", "host6", "host7",
                "host8", "host9", "host10", "host11"]
server-ports = ["10000", "10000", "10000", "10000",
                "10000", "10000", "10000", "10000",
                "10000", "10000", "10000", "10000"]

client-hosts = ["host0"]
