# Non-geo setup

hostnames = ["host0", "host1", "host2", "host3",
             "host4", "host5", "host6", "host7",
             "client0", "client1",
             "weak_0", "weak_1", "weak_2", "weak_3",
             "strong_0", "strong_1", "strong_2", "strong_3"]