# Hostname and geo-locationof all machines
hostnames = ["host0",   "host1",   "host2",   "host3",   "host4",   "host5",   "host6", "host7", ]
locations = ["us-west", "us-west", "us-west", "us-west", "eu-west", "eu-west", "au",    "au"]

# Binary and config file directories
remote-dir = ["/opt/chance/target_binary/", "/opt/chance/target_config/"]

# Envtest files and directories
config-files = ["host.toml"]
binary-files = ["envtest_client", "envtest_server"]
local-dir = ["/opt/chance/cob/target/debug/", "/opt/chance/cob/config/"]
