# Envtest files and directories
build = ["script/build_hotstuff.sh"]

log-dir = ["/users/Yunhao/log/"]
local-dir = ["/opt/chance/cob/target_systems/hotstuff/examples/", "/opt/chance/cob/target_systems/hotstuff/examples/"]
remote-dir = ["/opt/chance/target_binary/", "/opt/chance/target_config/"]

config-files = ["conf-hotstuff"]
binary-files = ["hotstuff-client", "hotstuff-app"]

client-args = ["/opt/chance/target_config/conf-hotstuff/hotstuff.gen.conf",
               "/users/Yunhao/log/log/client$1.log"]
server-args = ["/opt/chance/target_config/conf-hotstuff/hotstuff.gen.conf",
               "--conf",
               "/opt/chance/target_config/conf-hotstuff/hotstuff.gen-sec??.conf"]