default-duration = ["60000"]

hostnames = ["client0", "client1",
             "strong_0", "strong_1", "strong_2", "strong_3", "strong_4_0",
             "strong_4_1", "strong_5", "strong_6", "strong_7_0", "strong_7_1",
             "strong_8", "strong_9", "strong_10", "strong_11_0", "strong_11_1",
             "weak_0", "weak_1", "weak_2", "weak_3", "weak_4_0",
             "weak_4_1", "weak_5", "weak_6", "weak_7_0", "weak_7_1",
             "weak_8", "weak_9", "weak_10", "weak_11_0", "weak_11_1",
             "host0", "host1", "host2", "host3", "host4",
             "host5", "host6", "host7", "host8", "host9",
             "host10", "host11", "host12", "host13", "host14",
             "host15", "host16", "host17", "host18", "host19"]

client-hosts = ["client0", "client1"]
server-hosts = ["host0", "host1", "host2", "host3", "host4",
                "host5", "host6", "host7", "host8", "host9",
                "host10", "host11", "host12", "host13", "host14",
                "host15", "host16", "host17", "host18", "host19"]

weak-bump-hosts = ["weak_0", "weak_1", "weak_2", "weak_3", "weak_4_0",
                   "weak_4_1", "weak_5", "weak_6", "weak_7_0", "weak_7_1",
                   "weak_8", "weak_9", "weak_10", "weak_11_0", "weak_11_1"]

strong-bump-hosts = ["strong_0", "strong_1", "strong_2", "strong_3", "strong_4_0",
                     "strong_4_1", "strong_5", "strong_6", "strong_7_0", "strong_7_1",
                     "strong_8", "strong_9", "strong_10", "strong_11_0", "strong_11_1"]

# Washington ["81", "54", "206", "76", "92", "92", "111", "77", "71", "71", "270", "163", "71", "2", "2"]
# London ["9", "115", "275", "2", "20", "20", "40", "9", "137", "137", "172", "243", "86", "76", "76"]
# Munich ["15", "126", "275", "34", "2", "2", "41", "16", "158", "158", "178", "220", "109", "92", "92"]
# Tokyo ["271", "139", "221", "243", "220", "220", "274", "272", "107", "107", "83", "2", "154", "163", "163"]

strong-bump-latency = ["81", "54", "206", "76", "92", "92", "111", "77", "71", "71", "270", "163", "71", "2", "2"]   # Washington
weak-bump-latency =   ["99", "115", "275", "2", "20", "20", "40", "9", "137", "137", "172", "243", "86", "76", "76"]  # London

build = ["script/build_themis_bump.sh"]

local-dir = ["/opt/chance/cob/target_systems/themis-src-anon-cob/Aequitas-hotstuff/libhotstuff/examples/", "/opt/chance/cob/target_systems/themis-src-anon-cob/Aequitas-hotstuff/libhotstuff/examples/"]
remote-dir = ["/opt/chance/target_binary/", "/opt/chance/target_config/"]
log-dir = ["/users/Yunhao/log/"]

config-files = ["conf-themis-large"]
binary-files = ["themis-2clients", "hotstuff-app", "speedbump", "bump_tc.sh"]

# Note that the last parameter needs an index to fill up the {}
server-args = ["/opt/chance/target_config/conf-themis-large/hotstuff.gen.conf"]
server-idx-arg = ["/opt/chance/target_config/conf-themis-large/hotstuff.gen-sec", ".conf"]

client-args = ["/opt/chance/target_config/conf-themis-large/weak.gen.conf",
               "/opt/chance/target_config/conf-themis-large/strong.gen.conf"]

weak-bump-args = ["/opt/chance/target_config/conf-themis-large/weak.gen.conf",
                  "/opt/chance/target_config/conf-themis-large/hotstuff.gen.conf"]

strong-bump-args = ["/opt/chance/target_config/conf-themis-large/strong.gen.conf",
                    "/opt/chance/target_config/conf-themis-large/hotstuff.gen.conf"]
