# Hostname of all machines
hostnames = ["client1", "client2", "client3", "server1", "server2", "server3"]

# Geo-location of all machines
locations = ["us-west", "eu-west", "au", "us-west", "eu-west", "au"]