hostnames = ["client0", "client1",
             "host0", "host1", "host2", "host3",
             "weak_0", "weak_1", "weak_2", "weak_3",
             "strong_0", "strong_1", "strong_2", "strong_3"]

client-hosts = ["client0", "client1"]
server-hosts = ["host0", "host1", "host2", "host3"]

weak-bump-hosts =   ["weak_0", "weak_1", "weak_2", "weak_3"]
weak-bump-latency = ["2",      "160",    "192",    "229"]

strong-bump-hosts  =  ["strong_0", "strong_1", "strong_2", "strong_3"]
strong-bump-latency = ["2",        "147",      "185",      "216"]

build = ["script/build_pompe_bump.sh"]

local-dir = ["/opt/chance/cob/target_systems/pompe-bumped/examples/", "/opt/chance/cob/target_systems/pompe-bumped/examples/"]
remote-dir = ["/opt/chance/target_binary/", "/opt/chance/target_config/"]
log-dir = ["/users/Yunhao/log/"]

config-files = ["conf-pompe"]
binary-files = ["pompe-unbias-2clients", "pompe-app", "speedbump", "bump_tc.sh"]

# Note that the last parameter needs an index to fill up the {}
server-args = ["/opt/chance/target_config/conf-pompe/hotstuff.gen.conf"]
server-idx-arg = ["/opt/chance/target_config/conf-pompe/hotstuff.gen-sec", ".conf"]

client-args = ["/opt/chance/target_config/conf-pompe/weak.gen.conf",
               "/opt/chance/target_config/conf-pompe/strong.gen.conf"]

weak-bump-args = ["/opt/chance/target_config/conf-pompe/weak.gen.conf",
                    "/opt/chance/target_config/conf-pompe/hotstuff.gen.conf"]

strong-bump-args = ["/opt/chance/target_config/conf-pompe/strong.gen.conf",
                    "/opt/chance/target_config/conf-pompe/hotstuff.gen.conf"]
