# Envtest files and directories
client-hosts = ["client0"]
server-hosts = ["host0", "host1", "host2", "host3"]
bump-hosts  =  ["weak_0",   "weak_1",   "weak_2",   "weak_3",
                "strong_0", "strong_1", "strong_2", "strong_3"]
bump-latency = ["2",       "147",      "185",      "216",
                "2",       "160",      "192",      "229"]
bump-idx     = ["0",       "1",        "2",        "3",
                "0",       "1",        "2",        "3"]

build = ["script/build_pompe_bump.sh"]

local-dir = ["/opt/chance/cob/target_systems/pompe-bumped/examples/", "/opt/chance/cob/target_systems/pompe-bumped/examples/"]
remote-dir = ["/opt/chance/target_binary/", "/opt/chance/target_config/"]
log-dir = ["/users/Yunhao/log/"]

config-files = ["conf-pompe"]
binary-files = ["pompe-client", "pompe-app", "speedbump", "bump_tc.sh"]

# Note that the last parameter needs an index to fill up the {}
server-args = ["/opt/chance/target_config/conf-pompe/hotstuff.gen.conf"]
server-idx-arg = ["/opt/chance/target_config/conf-pompe/hotstuff.gen-sec", ".conf"]


client-args = ["/opt/chance/target_config/conf-pompe/bump0.gen.conf"]

bump-args = ["/opt/chance/target_config/conf-pompe/bump0.gen.conf",
             "/opt/chance/target_config/conf-pompe/hotstuff.gen.conf"]

# Obsolete
#bump-idx-arg = ["/opt/chance/target_config/conf-hotstuff/bump0.gen-sec", ".conf"]