# Envtest files and directories
client-hosts = ["host4", "host5", "host6", "host7"]
server-hosts = ["host0", "host1", "host2", "host3"]

build = ["script/build_pompe.sh"]

local-dir = ["/opt/chance/cob/target_systems/pompe/examples/", "/opt/chance/cob/target_systems/pompe/examples/"]
remote-dir = ["/opt/chance/target_binary/", "/opt/chance/target_config/"]
log-dir = ["/users/Yunhao/log/"]

config-files = ["conf-pompe"]
binary-files = ["pompe-client", "pompe-app"]

client-args = ["/opt/chance/target_config/conf-hotstuff/hotstuff.gen.conf"]
# Note that the last parameter needs an index to fill up the {}
server-args = ["/opt/chance/target_config/conf-hotstuff/hotstuff.gen.conf"]
server-idx-arg = ["/opt/chance/target_config/conf-hotstuff/hotstuff.gen-sec", ".conf"]